libs["glfw"] = "%{wks.location}/Vendor/HydroFramework/Vendor/glfw"
libs["Hydro"] = "%{wks.location}/Vendor/HydroFramework"
libs["stb"] = "%{wks.location}/Vendor/HydroFramework/Vendor/stb"
libs["glad"] = "%{wks.location}/Vendor/HydroFramework/Vendor/glad"
libs["spdlog"] = "%{wks.location}/Vendor/HydroFramework/External/spdlog"
libs["shaderc"] = "%{wks.location}/Vendor/HydroFramework/Vendor/shaderc"
libs["glslc"] = "%{wks.location}/Vendor/HydroFramework/Vendor/shaderc/glslc"
libs["libshaderc"] = "%{wks.location}/Vendor/HydroFramework/Vendor/shaderc/libshaderc"
libs["libshaderc_util"] = "%{wks.location}/Vendor/HydroFramework/Vendor/shaderc/libshaderc_util"

include "Hydro.lua"
include "Vendor/glfw/glfw.lua"
include "Vendor/stb/stb.lua"
include "Vendor/glad/glad.lua"
--include "Vendor/shaderc/libshaderc/libshaderc.lua"
--include "Vendor/shaderc/libshaderc_util/libshaderc_util.lua"
