libs["glfw"] = "%{wks.location}/Vendor/HydroFramework/Vendor/glfw"
libs["Hydro"] = "%{wks.location}/Vendor/HydroFramework"
libs["stb"] = "%{wks.location}/Vendor/HydroFramework/Vendor/stb"
libs["glad"] = "%{wks.location}/Vendor/HydroFramework/Vendor/glad"
libs["spdlog"] = "%{wks.location}/Vendor/HydroFramework/Vendor/spdlog"
libs["yaml"] = "%{wks.location}/Vendor/HydroFramework/Vendor/yaml-cpp"
libs["ufbx"] = "%{wks.location}/Vendor/HydroFramework/Vendor/ufbx" 
libs["box2d"] = "%{wks.location}/Vendor/HydroFramework/Vendor/box2d"
libs["imgui"] = "%{wks.location}/Vendor/HydroFramework/Vendor/imgui"

include "Hydro.lua"
include "Vendor/glfw/glfw.lua"
include "Vendor/stb/stb.lua"
include "Vendor/glad/glad.lua"
include "Vendor/spdlog/spdlog.lua"
include "Vendor/yaml-cpp/yaml-cpp.lua"
include "Vendor/ufbx/ufbx.lua"
include "Vendor/box2d/box2d.lua"
include "Vendor/imgui/imgui.lua"