libs["glfw"] = "%{wks.location}/Vendor/HydroFramework/Vendor/glfw"
libs["Hydro"] = "%{wks.location}/Vendor/HydroFramework"
libs["stb"] = "%{wks.location}/Vendor/HydroFramework/Vendor/stb"
libs["glad"] = "%{wks.location}/Vendor/HydroFramework/Vendor/glad"
libs["spdlog"] = "%{wks.location}/Vendor/HydroFramework/External/spdlog"
libs["libshaderc"] = "%{wks.location}/Vendor/HydroFramework/Vendor/shaderc/libshaderc"

include "Hydro.lua"
include "Vendor/glfw/glfw.lua"
include "Vendor/stb/stb.lua"
include "Vendor/glad/glad.lua"
