#pragma once
#include "Core/EntryPoint.h"
#include "Core/Application.h"
#include "Core/Image.h"
#include "Core/ImageFormat.h"
#include "Core/Window.h"
#include "Core/SharedPointer.h"
#include "Core/Buffer.h"
#include "Core/Renderer.h"
#include "Core/Vertex.h"
#include "Core/Input.h"
#include "Core/Color.h"
#include "Core/KeyCodes.h"
#include "Core/Log.h"
#include "Core/LogCategory.h"
#include "Core/LogVerbosity.h"
#include "Core/Filesystem.h"
#include "Serialization/ApplicationConfigurationSerializer.h"

#include "Core/Shader.h"

